Pierre/Models/Flavor.cs
using System.Collections.Generic;
using System;

namespace Pierre.Models
{
    public class Flavor
    {
        public Flavor()
        {
            this.JoinEntities = new HashSet<FlavorTreat>();
        }

        public int FlavorId { get; set; }
        public string FlavorName { get; set; }
        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<FlavorTreat> JoinEntities { get;}
    }
}

Pierre/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Pierre.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Pierre.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierreContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PierreContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View();
    }
    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor, int TreatId)
    {
    var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    var currentUser = await _userManager.FindByIdAsync(userId);
    flavor.User = currentUser;
    _db.Flavors.Add(flavor);
    _db.SaveChanges();
    if (TreatId != 0)
    {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
    }
    _db.SaveChanges();
    return RedirectToAction("Index");
    }
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
          .Include(flavor => flavor.JoinEntities)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }
        public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor, int TreatId)
    {
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
      _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Pierre/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Pierre.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Pierre.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierreContext _db;
    public TreatsController(PierreContext db)
    {
      _db = db;
    }
    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }
    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Pierre/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model Pierre.Models.Flavor

<h2>Add a treat</h2>

<h4>Add a treat to this flavor type:</h4>
<br>
<h4>@Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)
  <br>
  @Html.Label("Select treat: ")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Save" />
}
<nav class="navbar fixed-bottom navbar-expand-xl navbar-dark bg-light">
  <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</button>
  <button  class="btn btn-lg btn-outline-dark">@Html.ActionLink("All Flavors", "Index")</button>
  @if (User.Identity.IsAuthenticated)
  {
    @using (Html.BeginForm("LogOff", "Account"))
    {
      <input type="submit" class="ms-5 btn btn-lg btn-danger" value="Logout"/>
    }
  }
</nav>

Pierre/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model Pierre.Models.Flavor
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.AspNetCore.Identity;
@using Pierre.Models;
@using System.Threading.Tasks;
@using Pierre.ViewModels;
@using Microsoft.AspNetCore.Authorization;
@using Microsoft.AspNetCore.Mvc.RazorPages;
@using Microsoft.Extensions.Logging;

<h4>Add a new flavor</h4>

@using (Html.BeginForm())
{
  @Html.Label("Flavor Name:")
  @Html.TextBoxFor(model => model.FlavorName)
  <br>
  @Html.Label("Add a Treat, if available, to this Flavor type:")
  @Html.DropDownList("TreatId")
  <br>
  <input type="submit" value="Add new flavor" class="btn btn-info" />
}

<nav class="navbar fixed-bottom navbar-expand-xl navbar-dark bg-light">
  <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</button>
  <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("All Flavors", "Index")</button>
  @using (Html.BeginForm("LogOff", "Account"))
  {
    <input type="submit" class="ms-5 btn btn-lg btn-danger" value="Logout"/>
  }
</nav>

Pierre/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Pierre.Models.Flavor

<h2>Are you sure you want to delete this flavor?</h2>

@Html.DisplayName("Flavor"): @Html.DisplayFor(model => model.FlavorName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
<nav class="navbar fixed-bottom navbar-expand-xl navbar-dark bg-light">
  <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</button>
  <button  class="btn btn-lg btn-outline-dark">@Html.ActionLink("All Flavors", "Index")</button>
  @using (Html.BeginForm("LogOff", "Account"))
  {
    <input type="submit" class="ms-5 btn btn-lg btn-danger" value="Logout"/>
  }
</nav>

Pierre/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model Pierre.Models.Flavor

<h2>Flavor Details</h2>
<hr />
<h3>Category: @Html.DisplayFor(model => model.FlavorName)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>No treats in stock with this flavor type. Check back soon!</p>
}
else
{
  <h4>We carry the following treats for this category!</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@Html.ActionLink($"{join.Treat.TreatName}", "Details", "Treats", new { id = join.Treat.TreatId }, null)</li>
    @if (User.Identity.IsAuthenticated)
    {
      @using (Html.BeginForm("DeleteTreat", "Flavors"))
      {
        @Html.Hidden("joinId", @join.FlavorTreatId)
        <input type="submit" value="Delete"/>
      }
    }
  }
  </ul>
}

<nav class="navbar fixed-bottom navbar-expand-xl navbar-dark bg-light">
  <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</button>
  <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("All Flavors", "Index")</button>
  @if (User.Identity.IsAuthenticated)
  {
    <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("Add a Treat", "AddTreat", new { id = Model.FlavorId })</button>
    <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</button>
    <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</button>
    @using (Html.BeginForm("LogOff", "Account"))
    {
      <input type="submit" class="ms-5 btn btn-lg btn-danger" value="Logout"/>
    }
  }
  else
  {
    <button class="ms-5 btn btn-lg btn-outline-dark">@Html.ActionLink("Login or Register", "Index", "Account")</button>
  }
</nav>

Pierre/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Pierre.Models.Flavor

<h2>Edit</h2>

<h4>Edit this flavor: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  <p>@Html.Label("Change Name:")</p>
  <p>@Html.EditorFor(model => model.FlavorName)</p>
  <hr>
  <p>@Html.Label("Add a Treat, if available, to this Flavor type:")</p>
  <p>@Html.DropDownList("TreatId")</p>
  <br>
  <input type="submit" class="btn btn-primary" value="Save" />
}
<nav class="navbar fixed-bottom navbar-expand-xl navbar-dark bg-light">
  <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</button>
  <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("All Flavors", "Index")</button>
  @using (Html.BeginForm("LogOff", "Account"))
  {
    <input type="submit" class="ms-5 btn btn-lg btn-danger" value="Logout"/>
  }
</nav>

Pierre/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using Pierre.Models
@model IEnumerable<Pierre.Models.Flavor>

<h1 class="text-center">Flavors of Pierre's</h1>
<hr>

@if (@Model.Count() == 0 && User.Identity.IsAuthenticated)
{
  <h3>No flavors have been added yet!</h3>
  <h4>Add a flavor using the "Add new flavor" button.</h4>
}
else if (@Model.Count() == 0)
{
  <h3>No flavors have been added, sign in to add one!</h3>
}
<ul>
  @foreach(Flavor flavor in Model)
  {
    <li>@Html.ActionLink($"{flavor.FlavorName}", "Details", new { id = flavor.FlavorId })</li>
  }
</ul>

<nav class="navbar fixed-bottom navbar-expand-xl navbar-dark bg-light">
  <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</button>
  @if (User.Identity.IsAuthenticated)
  {
    <button class="btn btn-lg btn-outline-dark">@Html.ActionLink("Add new Flavor", "Create")</button>
    @using (Html.BeginForm("LogOff", "Account"))
    {
      <input type="submit" class="ms-5 btn btn-lg btn-danger" value="Logout"/>
    }
  }
  else
  {
    <button class="ms-5 btn btn-lg btn-outline-dark">@Html.ActionLink("Login or Register", "Index", "Account")</button>
  }
</nav>